database:
  image: postgres
  container_name: database
  environment:
    POSTGRES_DB: ${DB_NAME}
    POSTGRES_PASSWORD: ${DB_PASSWORD}
    POSTGRES_USER: ${DB_USERNAME}
  ports:
    - 5432:${DB_PORT}
